[features]
seeds = false
[programs.localnet]
solana_twitter = "2YdvgszBrPt3Ta3CPn27LAtbb8o53YRvbGKfQVVS8fdS"

[programs.devnet]
solana_twitter = "2YdvgszBrPt3Ta3CPn27LAtbb8o53YRvbGKfQVVS8fdS"

[programs.mainnet]
solana_twitter = "2YdvgszBrPt3Ta3CPn27LAtbb8o53YRvbGKfQVVS8fdS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
my-custom-script = "echo 'Hello world!'"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
